---
title: "Getting started with epidemic modelling"
output:
  bookdown::html_vignette2:
    fig_caption: yes
    code_folding: show
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{Getting started with epidemic modelling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  dpi = 150
)
```

```{r setup}
library(epidemics)
library(data.table)
library(ggplot2)
```

## Prepare population and initial conditions

Prepare population and contact data.

```{r}
# load contact and population data from socialmixr::polymod
polymod <- socialmixr::polymod
contact_data <- socialmixr::contact_matrix(
  polymod,
  countries = "United Kingdom",
  age.limits = c(0, 20, 40),
  symmetric = TRUE
)

# prepare contact matrix
contact_matrix <- t(contact_data$matrix)
# prepare the demography vector
demography_vector <- contact_data$demography$population
names(demography_vector) <- rownames(contact_matrix)

# view contact matrix and demography
contact_matrix

demography_vector
```

Prepare initial conditions for each age group.

```{r}
# initial conditions: 0-20 are more infected than other groups
initial_conditions <- rbind(
  c(S = 0.99999, I = 0.00001, R = 0, V = 0),
  c(S = 0.99999, I = 0.00001, R = 0, V = 0),
  c(S = 0.99999, I = 0.00001, R = 0, V = 0)
)

# assign rownames for clarity
rownames(initial_conditions) <- rownames(contact_matrix)

# view initial conditions
initial_conditions
```

Prepare a population as a `population` class object.

```{r}
new_pop <- population(
  name = "UK",
  contact_matrix = contact_matrix,
  demography_vector = demography_vector,
  initial_conditions = initial_conditions
)

new_pop
```

## Prepare interventions

Prepare an intervention to simulate school closures.

```{r}
# prepare an intervention with a differential effect on age groups
close_schools <- intervention(
  name = "School closure",
  time_begin = 200,
  time_end = 300,
  contact_reduction = c(0.5, 0.001, 0.001)
)

close_schools
```

## Run epidemic model

```{r}
# run an epidemic model
output <- epi_demic(
  population = new_pop,
  infectious_period = rep(6, 3), # age-specific infectious periods are similar
  R0 = c(1.2, 1.2, 1.2), # same R0 in all ages
  intervention = close_schools,
  nu = rep(0, 3), # no vaccination
  t_max = 800,
  t_increment = 1
)
```

## Prepare data and visualise infections

```{r}
# rename age groups
age_groups <- rownames(contact_matrix)
output[, age_group := fcase(
  age_group == 1, age_groups[1],
  age_group == 2, age_groups[2],
  age_group == 3, age_groups[3]
)]
```

Plot infections over time.

```{r fig.width=4, fig.height=3}
# plot figure of epidemic curve
ggplot(
  output[compartment == "infected", ],
  aes(
    x = time,
    y = value,
    col = age_group,
    group = interaction(compartment, age_group)
  )
) +
  geom_line() +
  annotate(
    geom = "rect",
    xmin = close_schools$time_begin,
    xmax = close_schools$time_end,
    ymin = 0, ymax = 250e3,
    fill = alpha("red", alpha = 0.2),
    lty = "dashed"
  ) +
  annotate(
    geom = "text",
    x = mean(c(close_schools$time_begin, close_schools$time_end)),
    y = 175e3,
    angle = 90,
    label = "School closure"
  ) +
  scale_y_continuous(
    labels = scales::comma
  ) +
  scale_colour_brewer(
    palette = "Dark2",
    name = "Age group"
  ) +
  expand_limits(
    y = c(0, 250e3)
  ) +
  coord_cartesian(
    expand = FALSE
  ) +
  theme_classic() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Simulation time (days)",
    y = "Total individuals infected"
  )
```
