---
title: "finalsize_comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{finalsize_comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(epidemics)
library(finalsize)

library(dplyr)
library(tibble)
library(tidyr)
library(ggplot2)
library(socialmixr)
```

# Comparison with simple SEIR-V model

## SEIR-V model

```{r}
# load contact and population data from socialmixr::polymod
polymod <- polymod
contact_data <- contact_matrix(
  polymod,
  countries = "United Kingdom",
  age.limits = c(0, 20, 40),
  symmetric = TRUE
)

# prepare contact matrix
contact_matrix <- t(contact_data$matrix)

# prepare the demography vector
demography_vector <- contact_data$demography$population
names(demography_vector) <- rownames(contact_matrix)

# initial conditions: one in every 1 million is infected
initial_i <- 1e-6
initial_conditions <- c(
  S = 1 - initial_i, E = 0, I = initial_i, R = 0, V = 0
)

# build for all age groups
initial_conditions <- rbind(
  initial_conditions,
  initial_conditions,
  initial_conditions
)
rownames(initial_conditions) <- rownames(contact_matrix)

# prepare the population to model as affected by the epidemic
uk_population <- population(
  name = "UK",
  contact_matrix = contact_matrix,
  demography_vector = demography_vector,
  initial_conditions = initial_conditions
)

# simulate a pandemic, with an R0,
# an infectious period, and an pre-infectious period
pandemic_influenza <- infection(
  r0 = 1.5,
  preinfectious_period = 3,
  infectious_period = 7
)

# run an epidemic model using `epidemic_default_*()`
output <- epidemic_default_cpp(
  population = uk_population,
  infection = pandemic_influenza,
  time_end = 600, increment = 1.0
)

plot_dat <- filter(output, compartment %in% c("susceptible", "recovered"))

ggplot(plot_dat) +
  geom_line(aes(x = time, y = value, colour = compartment)) +
  facet_grid(rows = vars(demography_group))
```

```{r}
# Calculate the attack rate using the fraction of recovered
finalsize_dat <- tibble(
  demography_group = names(demography_vector),
  value = epidemic_size(output) / demography_vector
)

finalsize_dat
```

## Final size

```{r}
# Define population in each age group
scalar <- max(eigen(contact_data$matrix)$values)
contact_matrix <- (contact_data$matrix / demography_vector) / scalar

# Define susceptibility of each group
susceptibility <- matrix(
  data = c(1.0, 1, 1),
  nrow = length(demography_vector),
  ncol = 1
)

# Assume uniform susceptibility within age groups
p_susceptibility <- matrix(
  data = 1.0,
  nrow = length(demography_vector),
  ncol = 1
)

# Calculate the proportion of individuals infected in each age group
dat <- final_size(
  r0 = pandemic_influenza$r0,
  contact_matrix = contact_matrix,
  demography_vector = demography_vector,
  susceptibility = susceptibility,
  p_susceptibility = p_susceptibility
)

dat <- select(dat, demo_grp, final_size = p_infected)

finalsize_dat %>%
  select(demo_grp = demography_group, seir_v = value) %>%
  left_join(dat)
```

## Susceptibility

- Do we want to discuss susceptibility structure?

## Vaccination

Final size does not allow us to implement a dynamic vaccination calendar, but if the vaccine is delivered before the main wave, then we the overall outcome is comparable. 

```{r}
# prepare a vaccination object
vaccinate_elders <- vaccination(
  name = "vaccinate elders",
  time_begin = matrix(1, nrow(contact_matrix)),
  time_end = matrix(150, nrow(contact_matrix)),
  nu = matrix(c(0.0, 0.0, 0.001))
)

output <- epidemic_default_cpp(
  population = uk_population,
  infection = pandemic_influenza,
  vaccination = vaccinate_elders,
  time_end = 600, increment = 1.0
)

# Calculate the attack rate using the fraction of recovered
finalsize_dat <- tibble(
  demography_group = names(demography_vector),
  value = epidemic_size(output) / demography_vector
)

finalsize_dat
```

```{r}
# Proportion of the individuals vaccinated
p_vacc <- filter(output, compartment == "vaccinated", time == max(time))
p_vacc <- p_vacc$value / demography_vector

susceptibility <- matrix(
  data = 1,
  nrow = length(demography_vector),
  ncol = 2,
  dimnames = list(
    names(demography_vector),
    c("unvaccinated", "vaccinated")
  )
)

# Second column holds the vaccinated (who are protected fully)
susceptibility[, "vaccinated"] <- 0

# Assume uniform susceptibility within age groups
p_susceptibility <- matrix(
  data = 1.0,
  nrow = length(demography_vector),
  ncol = 2,
  dimnames = list(
    names(demography_vector),
    c("unvaccinated", "vaccinated")
  )
)
p_susceptibility[, "vaccinated"] <- p_vacc
p_susceptibility[, "unvaccinated"] <- 1 - p_vacc

# Calculate the proportion of individuals infected in each age group
dat1 <- final_size(
  r0 = pandemic_influenza$r0,
  contact_matrix = contact_matrix,
  demography_vector = demography_vector,
  susceptibility = susceptibility,
  p_susceptibility = p_susceptibility
)

# Final size returns the proportion infected in each susceptibility group
# (i.e. non vaccinated and vaccinated)
# here we calculate the proportion of infected for the age group as a whole
dat3 <- dat1 %>%
  select(-susceptibility) %>%
  pivot_wider(names_from = susc_grp, values_from = p_infected)
fs <- dat3$unvaccinated * p_susceptibility[, "unvaccinated"]

finalsize_dat %>%
  select(demo_grp = demography_group, seir_v = value) %>%
  mutate(final_size = fs)
```
