// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_epidemics_RCPPEXPORTS_H_GEN_
#define RCPP_epidemics_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace epidemics {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("epidemics", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("epidemics", "_epidemics_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in epidemics");
            }
        }
    }

    inline Rcpp::List _sir_stochastic(const Rcpp::List& parameters) {
        typedef SEXP(*Ptr__sir_stochastic)(SEXP);
        static Ptr__sir_stochastic p__sir_stochastic = NULL;
        if (p__sir_stochastic == NULL) {
            validateSignature("Rcpp::List(*_sir_stochastic)(const Rcpp::List&)");
            p__sir_stochastic = (Ptr__sir_stochastic)R_GetCCallable("epidemics", "_epidemics__sir_stochastic");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p__sir_stochastic(Shield<SEXP>(Rcpp::wrap(parameters)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_epidemics_RCPPEXPORTS_H_GEN_
