// Generated by Rcpp and edited manually to allow header export

#ifndef RCPP_epidemics_H_GEN_
#define RCPP_epidemics_H_GEN_

#include "epidemics_RcppExports.h"
#include "sir_stochastic.h"

#endif // RCPP_epidemics_H_GEN_
