// Automatically generated by odin 1.5.11 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
typedef struct seirv_model_internal {
  double beta;
  double *C;
  double *contact_reduction;
  double *contact_reduction_sum;
  double *contact_reduction_total;
  int dim_C;
  int dim_C_1;
  int dim_C_2;
  int dim_contact_reduction;
  int dim_contact_reduction_1;
  int dim_contact_reduction_2;
  int dim_contact_reduction_sum;
  int dim_contact_reduction_total;
  int dim_E;
  int dim_I;
  int dim_init_E;
  int dim_init_I;
  int dim_init_R;
  int dim_init_S;
  int dim_init_V;
  int dim_intervention_effect;
  int dim_intervention_effect_1;
  int dim_intervention_effect_2;
  int dim_intervention_end;
  int dim_intervention_start;
  int dim_lambda;
  int dim_lambda_prod;
  int dim_lambda_prod_1;
  int dim_lambda_prod_2;
  int dim_R;
  int dim_S;
  int dim_V;
  int dim_vax_end;
  int dim_vax_nu;
  int dim_vax_rate;
  int dim_vax_start;
  double gamma;
  double *init_E;
  double *init_I;
  double *init_R;
  double *init_S;
  double *init_V;
  double *initial_E;
  double *initial_I;
  double *initial_R;
  double *initial_S;
  double *initial_V;
  double *intervention_effect;
  double *intervention_end;
  double *intervention_start;
  double *lambda;
  double *lambda_prod;
  int n_age;
  int n_intervention;
  int offset_variable_I;
  int offset_variable_R;
  int offset_variable_V;
  double sigma;
  double *vax_end;
  double *vax_nu;
  double *vax_rate;
  double *vax_start;
} seirv_model_internal;
seirv_model_internal* seirv_model_get_internal(SEXP internal_p, int closed_error);
static void seirv_model_finalise(SEXP internal_p);
SEXP seirv_model_create(SEXP user);
void seirv_model_initmod_desolve(void(* odeparms) (int *, double *));
SEXP seirv_model_contents(SEXP internal_p);
SEXP seirv_model_set_user(SEXP internal_p, SEXP user);
SEXP seirv_model_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP seirv_model_use_dde_ptr);
SEXP seirv_model_metadata(SEXP internal_p);
SEXP seirv_model_initial_conditions(SEXP internal_p, SEXP t_ptr);
void seirv_model_rhs(seirv_model_internal* internal, double t, double * state, double * dstatedt, double * output);
void seirv_model_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal);
void seirv_model_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np);
SEXP seirv_model_rhs_r(SEXP internal_p, SEXP t, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void odin_set_dim(SEXP target, int rank, ...);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
double scalar_real(SEXP x, const char * name);
double odin_sum1(double *x, size_t from, size_t to);
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
seirv_model_internal* seirv_model_get_internal(SEXP internal_p, int closed_error) {
  seirv_model_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (seirv_model_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void seirv_model_finalise(SEXP internal_p) {
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal->C);
    R_Free(internal->contact_reduction);
    R_Free(internal->contact_reduction_sum);
    R_Free(internal->contact_reduction_total);
    R_Free(internal->init_E);
    R_Free(internal->init_I);
    R_Free(internal->init_R);
    R_Free(internal->init_S);
    R_Free(internal->init_V);
    R_Free(internal->initial_E);
    R_Free(internal->initial_I);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->initial_V);
    R_Free(internal->intervention_effect);
    R_Free(internal->intervention_end);
    R_Free(internal->intervention_start);
    R_Free(internal->lambda);
    R_Free(internal->lambda_prod);
    R_Free(internal->vax_end);
    R_Free(internal->vax_nu);
    R_Free(internal->vax_rate);
    R_Free(internal->vax_start);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP seirv_model_create(SEXP user) {
  seirv_model_internal *internal = (seirv_model_internal*) R_Calloc(1, seirv_model_internal);
  internal->C = NULL;
  internal->contact_reduction = NULL;
  internal->contact_reduction_sum = NULL;
  internal->contact_reduction_total = NULL;
  internal->init_E = NULL;
  internal->init_I = NULL;
  internal->init_R = NULL;
  internal->init_S = NULL;
  internal->init_V = NULL;
  internal->initial_E = NULL;
  internal->initial_I = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->initial_V = NULL;
  internal->intervention_effect = NULL;
  internal->intervention_end = NULL;
  internal->intervention_start = NULL;
  internal->lambda = NULL;
  internal->lambda_prod = NULL;
  internal->vax_end = NULL;
  internal->vax_nu = NULL;
  internal->vax_rate = NULL;
  internal->vax_start = NULL;
  internal->beta = NA_REAL;
  internal->C = NULL;
  internal->gamma = NA_REAL;
  internal->init_E = NULL;
  internal->init_I = NULL;
  internal->init_R = NULL;
  internal->init_S = NULL;
  internal->init_V = NULL;
  internal->intervention_effect = NULL;
  internal->intervention_end = NULL;
  internal->intervention_start = NULL;
  internal->n_age = NA_INTEGER;
  internal->n_intervention = NA_INTEGER;
  internal->sigma = NA_REAL;
  internal->vax_end = NULL;
  internal->vax_nu = NULL;
  internal->vax_start = NULL;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, seirv_model_finalise);
  UNPROTECT(1);
  return ptr;
}
static seirv_model_internal *seirv_model_internal_ds;
void seirv_model_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  seirv_model_internal_ds = seirv_model_get_internal(get_desolve_gparms(), 1);
}
SEXP seirv_model_contents(SEXP internal_p) {
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 62));
  SET_VECTOR_ELT(contents, 0, ScalarReal(internal->beta));
  SEXP C = PROTECT(allocVector(REALSXP, internal->dim_C));
  memcpy(REAL(C), internal->C, internal->dim_C * sizeof(double));
  odin_set_dim(C, 2, internal->dim_C_1, internal->dim_C_2);
  SET_VECTOR_ELT(contents, 1, C);
  SEXP contact_reduction = PROTECT(allocVector(REALSXP, internal->dim_contact_reduction));
  memcpy(REAL(contact_reduction), internal->contact_reduction, internal->dim_contact_reduction * sizeof(double));
  odin_set_dim(contact_reduction, 2, internal->dim_contact_reduction_1, internal->dim_contact_reduction_2);
  SET_VECTOR_ELT(contents, 2, contact_reduction);
  SEXP contact_reduction_sum = PROTECT(allocVector(REALSXP, internal->dim_contact_reduction_sum));
  memcpy(REAL(contact_reduction_sum), internal->contact_reduction_sum, internal->dim_contact_reduction_sum * sizeof(double));
  SET_VECTOR_ELT(contents, 3, contact_reduction_sum);
  SEXP contact_reduction_total = PROTECT(allocVector(REALSXP, internal->dim_contact_reduction_total));
  memcpy(REAL(contact_reduction_total), internal->contact_reduction_total, internal->dim_contact_reduction_total * sizeof(double));
  SET_VECTOR_ELT(contents, 4, contact_reduction_total);
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_C));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_C_1));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_C_2));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_contact_reduction));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_contact_reduction_1));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_contact_reduction_2));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_contact_reduction_sum));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_contact_reduction_total));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_E));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_init_E));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_init_I));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_init_R));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_init_S));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_init_V));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_intervention_effect));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_intervention_effect_1));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_intervention_effect_2));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_intervention_end));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_intervention_start));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_lambda));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_lambda_prod));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_lambda_prod_1));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_lambda_prod_2));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_V));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_vax_end));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_vax_nu));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_vax_rate));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_vax_start));
  SET_VECTOR_ELT(contents, 36, ScalarReal(internal->gamma));
  SEXP init_E = PROTECT(allocVector(REALSXP, internal->dim_init_E));
  memcpy(REAL(init_E), internal->init_E, internal->dim_init_E * sizeof(double));
  SET_VECTOR_ELT(contents, 37, init_E);
  SEXP init_I = PROTECT(allocVector(REALSXP, internal->dim_init_I));
  memcpy(REAL(init_I), internal->init_I, internal->dim_init_I * sizeof(double));
  SET_VECTOR_ELT(contents, 38, init_I);
  SEXP init_R = PROTECT(allocVector(REALSXP, internal->dim_init_R));
  memcpy(REAL(init_R), internal->init_R, internal->dim_init_R * sizeof(double));
  SET_VECTOR_ELT(contents, 39, init_R);
  SEXP init_S = PROTECT(allocVector(REALSXP, internal->dim_init_S));
  memcpy(REAL(init_S), internal->init_S, internal->dim_init_S * sizeof(double));
  SET_VECTOR_ELT(contents, 40, init_S);
  SEXP init_V = PROTECT(allocVector(REALSXP, internal->dim_init_V));
  memcpy(REAL(init_V), internal->init_V, internal->dim_init_V * sizeof(double));
  SET_VECTOR_ELT(contents, 41, init_V);
  SEXP initial_E = PROTECT(allocVector(REALSXP, internal->dim_E));
  memcpy(REAL(initial_E), internal->initial_E, internal->dim_E * sizeof(double));
  SET_VECTOR_ELT(contents, 42, initial_E);
  SEXP initial_I = PROTECT(allocVector(REALSXP, internal->dim_I));
  memcpy(REAL(initial_I), internal->initial_I, internal->dim_I * sizeof(double));
  SET_VECTOR_ELT(contents, 43, initial_I);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 44, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 45, initial_S);
  SEXP initial_V = PROTECT(allocVector(REALSXP, internal->dim_V));
  memcpy(REAL(initial_V), internal->initial_V, internal->dim_V * sizeof(double));
  SET_VECTOR_ELT(contents, 46, initial_V);
  SEXP intervention_effect = PROTECT(allocVector(REALSXP, internal->dim_intervention_effect));
  memcpy(REAL(intervention_effect), internal->intervention_effect, internal->dim_intervention_effect * sizeof(double));
  odin_set_dim(intervention_effect, 2, internal->dim_intervention_effect_1, internal->dim_intervention_effect_2);
  SET_VECTOR_ELT(contents, 47, intervention_effect);
  SEXP intervention_end = PROTECT(allocVector(REALSXP, internal->dim_intervention_end));
  memcpy(REAL(intervention_end), internal->intervention_end, internal->dim_intervention_end * sizeof(double));
  SET_VECTOR_ELT(contents, 48, intervention_end);
  SEXP intervention_start = PROTECT(allocVector(REALSXP, internal->dim_intervention_start));
  memcpy(REAL(intervention_start), internal->intervention_start, internal->dim_intervention_start * sizeof(double));
  SET_VECTOR_ELT(contents, 49, intervention_start);
  SEXP lambda = PROTECT(allocVector(REALSXP, internal->dim_lambda));
  memcpy(REAL(lambda), internal->lambda, internal->dim_lambda * sizeof(double));
  SET_VECTOR_ELT(contents, 50, lambda);
  SEXP lambda_prod = PROTECT(allocVector(REALSXP, internal->dim_lambda_prod));
  memcpy(REAL(lambda_prod), internal->lambda_prod, internal->dim_lambda_prod * sizeof(double));
  odin_set_dim(lambda_prod, 2, internal->dim_lambda_prod_1, internal->dim_lambda_prod_2);
  SET_VECTOR_ELT(contents, 51, lambda_prod);
  SET_VECTOR_ELT(contents, 52, ScalarInteger(internal->n_age));
  SET_VECTOR_ELT(contents, 53, ScalarInteger(internal->n_intervention));
  SET_VECTOR_ELT(contents, 54, ScalarInteger(internal->offset_variable_I));
  SET_VECTOR_ELT(contents, 55, ScalarInteger(internal->offset_variable_R));
  SET_VECTOR_ELT(contents, 56, ScalarInteger(internal->offset_variable_V));
  SET_VECTOR_ELT(contents, 57, ScalarReal(internal->sigma));
  SEXP vax_end = PROTECT(allocVector(REALSXP, internal->dim_vax_end));
  memcpy(REAL(vax_end), internal->vax_end, internal->dim_vax_end * sizeof(double));
  SET_VECTOR_ELT(contents, 58, vax_end);
  SEXP vax_nu = PROTECT(allocVector(REALSXP, internal->dim_vax_nu));
  memcpy(REAL(vax_nu), internal->vax_nu, internal->dim_vax_nu * sizeof(double));
  SET_VECTOR_ELT(contents, 59, vax_nu);
  SEXP vax_rate = PROTECT(allocVector(REALSXP, internal->dim_vax_rate));
  memcpy(REAL(vax_rate), internal->vax_rate, internal->dim_vax_rate * sizeof(double));
  SET_VECTOR_ELT(contents, 60, vax_rate);
  SEXP vax_start = PROTECT(allocVector(REALSXP, internal->dim_vax_start));
  memcpy(REAL(vax_start), internal->vax_start, internal->dim_vax_start * sizeof(double));
  SET_VECTOR_ELT(contents, 61, vax_start);
  SEXP nms = PROTECT(allocVector(STRSXP, 62));
  SET_STRING_ELT(nms, 0, mkChar("beta"));
  SET_STRING_ELT(nms, 1, mkChar("C"));
  SET_STRING_ELT(nms, 2, mkChar("contact_reduction"));
  SET_STRING_ELT(nms, 3, mkChar("contact_reduction_sum"));
  SET_STRING_ELT(nms, 4, mkChar("contact_reduction_total"));
  SET_STRING_ELT(nms, 5, mkChar("dim_C"));
  SET_STRING_ELT(nms, 6, mkChar("dim_C_1"));
  SET_STRING_ELT(nms, 7, mkChar("dim_C_2"));
  SET_STRING_ELT(nms, 8, mkChar("dim_contact_reduction"));
  SET_STRING_ELT(nms, 9, mkChar("dim_contact_reduction_1"));
  SET_STRING_ELT(nms, 10, mkChar("dim_contact_reduction_2"));
  SET_STRING_ELT(nms, 11, mkChar("dim_contact_reduction_sum"));
  SET_STRING_ELT(nms, 12, mkChar("dim_contact_reduction_total"));
  SET_STRING_ELT(nms, 13, mkChar("dim_E"));
  SET_STRING_ELT(nms, 14, mkChar("dim_I"));
  SET_STRING_ELT(nms, 15, mkChar("dim_init_E"));
  SET_STRING_ELT(nms, 16, mkChar("dim_init_I"));
  SET_STRING_ELT(nms, 17, mkChar("dim_init_R"));
  SET_STRING_ELT(nms, 18, mkChar("dim_init_S"));
  SET_STRING_ELT(nms, 19, mkChar("dim_init_V"));
  SET_STRING_ELT(nms, 20, mkChar("dim_intervention_effect"));
  SET_STRING_ELT(nms, 21, mkChar("dim_intervention_effect_1"));
  SET_STRING_ELT(nms, 22, mkChar("dim_intervention_effect_2"));
  SET_STRING_ELT(nms, 23, mkChar("dim_intervention_end"));
  SET_STRING_ELT(nms, 24, mkChar("dim_intervention_start"));
  SET_STRING_ELT(nms, 25, mkChar("dim_lambda"));
  SET_STRING_ELT(nms, 26, mkChar("dim_lambda_prod"));
  SET_STRING_ELT(nms, 27, mkChar("dim_lambda_prod_1"));
  SET_STRING_ELT(nms, 28, mkChar("dim_lambda_prod_2"));
  SET_STRING_ELT(nms, 29, mkChar("dim_R"));
  SET_STRING_ELT(nms, 30, mkChar("dim_S"));
  SET_STRING_ELT(nms, 31, mkChar("dim_V"));
  SET_STRING_ELT(nms, 32, mkChar("dim_vax_end"));
  SET_STRING_ELT(nms, 33, mkChar("dim_vax_nu"));
  SET_STRING_ELT(nms, 34, mkChar("dim_vax_rate"));
  SET_STRING_ELT(nms, 35, mkChar("dim_vax_start"));
  SET_STRING_ELT(nms, 36, mkChar("gamma"));
  SET_STRING_ELT(nms, 37, mkChar("init_E"));
  SET_STRING_ELT(nms, 38, mkChar("init_I"));
  SET_STRING_ELT(nms, 39, mkChar("init_R"));
  SET_STRING_ELT(nms, 40, mkChar("init_S"));
  SET_STRING_ELT(nms, 41, mkChar("init_V"));
  SET_STRING_ELT(nms, 42, mkChar("initial_E"));
  SET_STRING_ELT(nms, 43, mkChar("initial_I"));
  SET_STRING_ELT(nms, 44, mkChar("initial_R"));
  SET_STRING_ELT(nms, 45, mkChar("initial_S"));
  SET_STRING_ELT(nms, 46, mkChar("initial_V"));
  SET_STRING_ELT(nms, 47, mkChar("intervention_effect"));
  SET_STRING_ELT(nms, 48, mkChar("intervention_end"));
  SET_STRING_ELT(nms, 49, mkChar("intervention_start"));
  SET_STRING_ELT(nms, 50, mkChar("lambda"));
  SET_STRING_ELT(nms, 51, mkChar("lambda_prod"));
  SET_STRING_ELT(nms, 52, mkChar("n_age"));
  SET_STRING_ELT(nms, 53, mkChar("n_intervention"));
  SET_STRING_ELT(nms, 54, mkChar("offset_variable_I"));
  SET_STRING_ELT(nms, 55, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 56, mkChar("offset_variable_V"));
  SET_STRING_ELT(nms, 57, mkChar("sigma"));
  SET_STRING_ELT(nms, 58, mkChar("vax_end"));
  SET_STRING_ELT(nms, 59, mkChar("vax_nu"));
  SET_STRING_ELT(nms, 60, mkChar("vax_rate"));
  SET_STRING_ELT(nms, 61, mkChar("vax_start"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(25);
  return contents;
}
SEXP seirv_model_set_user(SEXP internal_p, SEXP user) {
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 1);
  internal->beta = user_get_scalar_double(user, "beta", internal->beta, NA_REAL, NA_REAL);
  internal->gamma = user_get_scalar_double(user, "gamma", internal->gamma, NA_REAL, NA_REAL);
  internal->n_age = user_get_scalar_int(user, "n_age", internal->n_age, NA_REAL, NA_REAL);
  internal->n_intervention = user_get_scalar_int(user, "n_intervention", internal->n_intervention, NA_REAL, NA_REAL);
  internal->sigma = user_get_scalar_double(user, "sigma", internal->sigma, NA_REAL, NA_REAL);
  internal->dim_C_1 = internal->n_age;
  internal->dim_C_2 = internal->n_age;
  internal->dim_contact_reduction_1 = internal->n_intervention;
  internal->dim_contact_reduction_2 = internal->n_age;
  internal->dim_contact_reduction_sum = internal->n_age;
  internal->dim_contact_reduction_total = internal->n_age;
  internal->dim_E = internal->n_age;
  internal->dim_I = internal->n_age;
  internal->dim_init_E = internal->n_age;
  internal->dim_init_I = internal->n_age;
  internal->dim_init_R = internal->n_age;
  internal->dim_init_S = internal->n_age;
  internal->dim_init_V = internal->n_age;
  internal->dim_intervention_effect_1 = internal->n_intervention;
  internal->dim_intervention_effect_2 = internal->n_age;
  internal->dim_intervention_end = internal->n_intervention;
  internal->dim_intervention_start = internal->n_intervention;
  internal->dim_lambda = internal->n_age;
  internal->dim_lambda_prod_1 = internal->n_age;
  internal->dim_lambda_prod_2 = internal->n_age;
  internal->dim_R = internal->n_age;
  internal->dim_S = internal->n_age;
  internal->dim_V = internal->n_age;
  internal->dim_vax_end = internal->n_age;
  internal->dim_vax_nu = internal->n_age;
  internal->dim_vax_rate = internal->n_age;
  internal->dim_vax_start = internal->n_age;
  R_Free(internal->contact_reduction_sum);
  internal->contact_reduction_sum = (double*) R_Calloc(internal->dim_contact_reduction_sum, double);
  R_Free(internal->contact_reduction_total);
  internal->contact_reduction_total = (double*) R_Calloc(internal->dim_contact_reduction_total, double);
  R_Free(internal->initial_E);
  internal->initial_E = (double*) R_Calloc(internal->dim_E, double);
  R_Free(internal->initial_I);
  internal->initial_I = (double*) R_Calloc(internal->dim_I, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->initial_V);
  internal->initial_V = (double*) R_Calloc(internal->dim_V, double);
  R_Free(internal->lambda);
  internal->lambda = (double*) R_Calloc(internal->dim_lambda, double);
  R_Free(internal->vax_rate);
  internal->vax_rate = (double*) R_Calloc(internal->dim_vax_rate, double);
  internal->dim_C = internal->dim_C_1 * internal->dim_C_2;
  internal->dim_contact_reduction = internal->dim_contact_reduction_1 * internal->dim_contact_reduction_2;
  internal->dim_intervention_effect = internal->dim_intervention_effect_1 * internal->dim_intervention_effect_2;
  internal->dim_lambda_prod = internal->dim_lambda_prod_1 * internal->dim_lambda_prod_2;
  internal->init_E = (double*) user_get_array(user, false, internal->init_E, "init_E", NA_REAL, NA_REAL, 1, internal->dim_init_E);
  internal->init_I = (double*) user_get_array(user, false, internal->init_I, "init_I", NA_REAL, NA_REAL, 1, internal->dim_init_I);
  internal->init_R = (double*) user_get_array(user, false, internal->init_R, "init_R", NA_REAL, NA_REAL, 1, internal->dim_init_R);
  internal->init_S = (double*) user_get_array(user, false, internal->init_S, "init_S", NA_REAL, NA_REAL, 1, internal->dim_init_S);
  internal->init_V = (double*) user_get_array(user, false, internal->init_V, "init_V", NA_REAL, NA_REAL, 1, internal->dim_init_V);
  internal->intervention_end = (double*) user_get_array(user, false, internal->intervention_end, "intervention_end", NA_REAL, NA_REAL, 1, internal->dim_intervention_end);
  internal->intervention_start = (double*) user_get_array(user, false, internal->intervention_start, "intervention_start", NA_REAL, NA_REAL, 1, internal->dim_intervention_start);
  internal->offset_variable_I = internal->dim_E + internal->dim_S;
  internal->offset_variable_R = internal->dim_E + internal->dim_I + internal->dim_S;
  internal->offset_variable_V = internal->dim_E + internal->dim_I + internal->dim_R + internal->dim_S;
  internal->vax_end = (double*) user_get_array(user, false, internal->vax_end, "vax_end", NA_REAL, NA_REAL, 1, internal->dim_vax_end);
  internal->vax_nu = (double*) user_get_array(user, false, internal->vax_nu, "vax_nu", NA_REAL, NA_REAL, 1, internal->dim_vax_nu);
  internal->vax_start = (double*) user_get_array(user, false, internal->vax_start, "vax_start", NA_REAL, NA_REAL, 1, internal->dim_vax_start);
  R_Free(internal->contact_reduction);
  internal->contact_reduction = (double*) R_Calloc(internal->dim_contact_reduction, double);
  R_Free(internal->lambda_prod);
  internal->lambda_prod = (double*) R_Calloc(internal->dim_lambda_prod, double);
  internal->C = (double*) user_get_array(user, false, internal->C, "C", NA_REAL, NA_REAL, 2, internal->dim_C_1, internal->dim_C_2);
  for (int i = 1; i <= internal->dim_E; ++i) {
    internal->initial_E[i - 1] = internal->init_E[i - 1];
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    internal->initial_I[i - 1] = internal->init_I[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = internal->init_R[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->init_S[i - 1];
  }
  for (int i = 1; i <= internal->dim_V; ++i) {
    internal->initial_V[i - 1] = internal->init_V[i - 1];
  }
  internal->intervention_effect = (double*) user_get_array(user, false, internal->intervention_effect, "intervention_effect", NA_REAL, NA_REAL, 2, internal->dim_intervention_effect_1, internal->dim_intervention_effect_2);
  return R_NilValue;
}
SEXP seirv_model_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP seirv_model_use_dde_ptr) {
  return R_NilValue;
}
SEXP seirv_model_metadata(SEXP internal_p) {
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 5));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 5));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_E));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(variable_length, 4, ScalarInteger(internal->dim_V));
  SET_STRING_ELT(variable_names, 0, mkChar("S"));
  SET_STRING_ELT(variable_names, 1, mkChar("E"));
  SET_STRING_ELT(variable_names, 2, mkChar("I"));
  SET_STRING_ELT(variable_names, 3, mkChar("R"));
  SET_STRING_ELT(variable_names, 4, mkChar("V"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  UNPROTECT(2);
  return ret;
}
SEXP seirv_model_initial_conditions(SEXP internal_p, SEXP t_ptr) {
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_E + internal->dim_I + internal->dim_R + internal->dim_S + internal->dim_V));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->dim_S, internal->initial_E, internal->dim_E * sizeof(double));
  memcpy(state + internal->offset_variable_I, internal->initial_I, internal->dim_I * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_V, internal->initial_V, internal->dim_V * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void seirv_model_rhs(seirv_model_internal* internal, double t, double * state, double * dstatedt, double * output) {
  double * S = state + 0;
  double * E = state + internal->dim_S;
  double * I = state + internal->offset_variable_I;
  for (int i = 1; i <= internal->dim_I; ++i) {
    dstatedt[internal->offset_variable_I + i - 1] = internal->sigma * E[i - 1] - internal->gamma * I[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    dstatedt[internal->offset_variable_R + i - 1] = internal->gamma * I[i - 1];
  }
  for (int i = 1; i <= internal->dim_vax_rate; ++i) {
    internal->vax_rate[i - 1] = (t >= internal->vax_start[i - 1] && t < internal->vax_end[i - 1] ? internal->vax_nu[i - 1] / (double) S[i - 1] : 0);
  }
  for (int i = 1; i <= internal->dim_contact_reduction_1; ++i) {
    for (int j = 1; j <= internal->dim_contact_reduction_2; ++j) {
      internal->contact_reduction[i - 1 + internal->dim_contact_reduction_1 * (j - 1)] = (t > internal->intervention_start[i - 1] && t < internal->intervention_end[i - 1] ? internal->intervention_effect[internal->dim_intervention_effect_1 * (j - 1) + i - 1] : 0);
    }
  }
  for (int i = 1; i <= internal->dim_contact_reduction_sum; ++i) {
    internal->contact_reduction_sum[i - 1] = odin_sum2(internal->contact_reduction, 0, internal->dim_contact_reduction_1, i - 1, i, internal->dim_contact_reduction_1);
  }
  for (int i = 1; i <= internal->dim_contact_reduction_total; ++i) {
    internal->contact_reduction_total[i - 1] = 1 - fmin(internal->contact_reduction_sum[i - 1], 1);
  }
  for (int i = 1; i <= internal->dim_lambda_prod_1; ++i) {
    for (int j = 1; j <= internal->dim_lambda_prod_2; ++j) {
      internal->lambda_prod[i - 1 + internal->dim_lambda_prod_1 * (j - 1)] = internal->C[internal->dim_C_1 * (j - 1) + i - 1] * I[j - 1] * internal->beta * internal->contact_reduction_total[j - 1] * internal->contact_reduction_total[i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_lambda; ++i) {
    internal->lambda[i - 1] = odin_sum2(internal->lambda_prod, i - 1, i, 0, internal->dim_lambda_prod_2, internal->dim_lambda_prod_1);
  }
  for (int i = 1; i <= internal->dim_E; ++i) {
    dstatedt[internal->dim_S + i - 1] = internal->lambda[i - 1] * S[i - 1] - internal->sigma * E[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    dstatedt[0 + i - 1] = (internal->vax_rate[i - 1] + internal->lambda[i - 1] < 1 ? -((internal->lambda[i - 1] + internal->vax_rate[i - 1])) * S[i - 1] : -(S[i - 1]));
  }
  for (int i = 1; i <= internal->dim_V; ++i) {
    dstatedt[internal->offset_variable_V + i - 1] = (internal->vax_rate[i - 1] + internal->lambda[i - 1] < 1 ? internal->vax_rate[i - 1] * S[i - 1] : S[i - 1] * (1 - internal->lambda[i - 1]));
  }
}
void seirv_model_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal) {
  seirv_model_rhs((seirv_model_internal*)internal, t, state, dstatedt, NULL);
}
void seirv_model_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np) {
  seirv_model_rhs(seirv_model_internal_ds, *t, state, dstatedt, output);
}
SEXP seirv_model_rhs_r(SEXP internal_p, SEXP t, SEXP state) {
  SEXP dstatedt = PROTECT(allocVector(REALSXP, LENGTH(state)));
  seirv_model_internal *internal = seirv_model_get_internal(internal_p, 1);
  double *output = NULL;
  seirv_model_rhs(internal, scalar_real(t, "t"), REAL(state), REAL(dstatedt), output);
  UNPROTECT(1);
  return dstatedt;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void odin_set_dim(SEXP target, int rank, ...) {
  SEXP r_dim = PROTECT(allocVector(INTSXP, rank));
  int *dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t)rank; ++i) {
    dim[i] = va_arg(ap, int);
  }
  va_end(ap);

  setAttrib(target, R_DimSymbol, r_dim);
  UNPROTECT(1);
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for '%s'", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
                 (int)i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for '%s'", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
double scalar_real(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  double ret = 0.0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    ret = REAL(x)[0];
  } else {
    Rf_error("Expected a numeric value for '%s'", name);
  }
  return ret;
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  double tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
