## Automatically generated by odin 1.5.11 - do not edit
seirv_model_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "seirv_model_rhs_dde",
      rhs_desolve = "seirv_model_rhs_desolve",
      initmod_desolve = "seirv_model_initmod_desolve"),
    dll = "epidemics",
    user = c("beta", "C", "gamma", "init_E", "init_I", "init_R", "init_S",
             "init_V", "intervention_effect", "intervention_end",
             "intervention_start", "n_age", "n_intervention", "sigma",
             "vax_end", "vax_nu", "vax_start"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("seirv_model_rhs_dde", package = "epidemics")
        .C("seirv_model_rhs_desolve", package = "epidemics")
        .C("seirv_model_initmod_desolve", package = "epidemics")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("seirv_model_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "epidemics")
    },

    update_metadata = function() {
      meta <- .Call("seirv_model_metadata", private$ptr,
                    PACKAGE = "epidemics")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("seirv_model_create", user, PACKAGE = "epidemics")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/seirv_model.json", mustWork = TRUE,
                             package = "epidemics")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("seirv_model_set_user", private$ptr, user, PACKAGE = "epidemics")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("seirv_model_initial_conditions", private$ptr, t, PACKAGE = "epidemics")
    },

    rhs = function(t, y) {
      .Call("seirv_model_rhs_r", private$ptr, t, y, PACKAGE = "epidemics")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("seirv_model_contents", private$ptr, PACKAGE = "epidemics")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


seirv_model <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("seirv_model")
  seirv_model_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(seirv_model) <- "odin_generator"
attr(seirv_model, "generator") <- seirv_model_
