# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Run an age-structured SEIR-V epidemic model
#'
#' @description A compartmental model with an optional non-pharmaceutical
#' intervention and an optional vaccination regime. Allows heterogeneity in
#' social contact patterns, and variable sizes of demographic groups.
#' Also allows for group-specific initial proportions in each model
#' compartment, as well as group-specific vaccination start dates and
#' vaccination rates, and also group-specific effects of implementing a
#' non-pharmaceutical intervention.
#' The model only allows for single, population-wide rates of
#' transition between the 'susceptible' and 'exposed' compartments, between the
#' 'exposed' and 'infectious' compartments, and in the recovery rate.
#'
#' @param population An object of the `population` class, which holds a
#' population contact matrix, a demography vector, and the initial conditions
#' of each demographic group. See [population()].
#' @param beta The transmission rate \eqn{\beta}.
#' @param alpha The rate of transition from exposed to infectious \eqn{\alpha}.
#' @param gamma The recovery rate \eqn{\gamma}.
#' @param time_end The maximum time, defaults to 200.0.
#' @param intervention A non-pharmaceutical intervention applied during the
#' course of the epidemic, with a start and end time, and age-specific effect
#' on contacts. See [intervention()].
#' @param vaccination A vaccination regime followed during the
#' course of the epidemic, with a start and end time, and age-specific effect
#' on the transition of individuals from susceptible to vaccinated.
#' See [vaccination()].
#' @param increment The increment time, defaults to 0.1.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix (see [population()]).
#' The second list element is a vector of timesteps.
#' @keywords internal
.epidemic_default_cpp <- function(population, beta, alpha, gamma, intervention, vaccination, time_end = 200.0, increment = 0.1) {
    .Call(`_epidemics_epidemic_default_cpp`, population, beta, alpha, gamma, intervention, vaccination, time_end, increment)
}

#' @title Run the RIVM Vacamole model
#'
#' @description Vacamole is a deterministic, compartmental epidemic model built
#' by Kylie Ainslie and others at RIVM, the Dutch Public Health Institute for
#' the Covid-19 pandemic, with a focus on scenario modelling for
#' hospitalisation and vaccination.
#' Model code: https://github.com/kylieainslie/vacamole
#' Manuscript describing the model and its application:
#' https://doi.org/10.2807/1560-7917.ES.2022.27.44.2101090
#'
#' @details The original model has 8 conceptual compartments - four
#' epidemiological compartments (SEIR), three hospitalisation compartments
#' (H, ICU, ICU2H), and death - see the manuscript in Eurosurveillance.
#' Only infected individuals can enter the hospitalisation or death
#' compartments.
#' Vacamole was implemented as a stand-alone R package, and some versions have
#' been used to generate scenarios for the ECDC Covid-19 Scenario Hub.
#'
#' Individuals from the susceptible compartment may be vaccinated partially
#' or fully (assuming a two dose regimen), with only the second dose reducing
#' their probability of being infected, and of being hospitalised or dying.
#'
#' @param population An object of the `population` class, which holds a
#' population contact matrix, a demography vector, and the initial conditions
#' of each demographic group. See [population()].
#' @param beta The transmission rate \eqn{\beta} at which unvaccinated and
#' partially vaccinated individuals are infected by the disease.
#' @param beta_v The transmission rate \eqn{\beta_V} at which individuals who
#' have received two vaccine doses are infected by the disease.
#' @param alpha The rate of transition from exposed to infectious \eqn{\alpha}.
#' This is common to fully susceptible, partially vaccinated, and fully
#' vaccinated individuals (where fully vaccinated represents two doses).
#' @param omega The mortality rate of fully susceptible and partially
#' vaccinated and unprotected individuals.
#' @param omega_v The mortality rate of individuals who are protected by
#' vaccination.
#' @param eta The hospitalisation rate of fully susceptible and partially
#' vaccinated and unprotected individuals.
#' @param eta_v The hospitalisation rate of individuals who are protected by
#' vaccination.
#' @param gamma The recovery rate \eqn{\gamma}.
#' @param time_end The maximum time. See [epidemic()] for default value.
#' @param intervention A non-pharmaceutical intervention applied during the
#' course of the epidemic, with a start and end time, and age-specific effect
#' on contacts. See [intervention()].
#' @param vaccination A vaccination regime followed during the
#' course of the epidemic, with a group- and dose-specific start and end time,
#' and age-specific rates of delivery of first and second doses.
#' See [vaccination()].
#' @param increment The increment time. See [epidemic()] for default value.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix (see [population()]).
#' The second list element is a vector of timesteps.
#' @keywords internal
.epidemic_vacamole_cpp <- function(population, beta, beta_v, alpha, omega, omega_v, eta, eta_v, gamma, intervention, vaccination, time_end, increment) {
    .Call(`_epidemics_epidemic_vacamole_cpp`, population, beta, beta_v, alpha, omega, omega_v, eta, eta_v, gamma, intervention, vaccination, time_end, increment)
}

#' @title Compute the discrete probability of the truncated Erlang distribution
#'
#' @description A helper function that gives the probability of discrete values
#' from an Erlang distribution with a given shape and rate. The number of
#' values returned correspond to the number of discrete values over which the
#' cumulative probability reaches 0.99.
#'
#' @param shape A single integer-like number for the shape of the Erlang
#' distribution.
#' @param rate A single number for the rate of the Erlang distribution.
#' @return A vector of variable length giving the probability of each integer
#' value for a cumulative probability of 0.99.
#' @export
.prob_discrete_erlang <- function(shape = 5L, rate = 1.0) {
    .Call(`_epidemics_prob_discrete_erlang`, shape, rate)
}

