# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Run an age-structured SEIR-V epidemic ODE model using a Boost solver
#'
#' @description A compartmental model with an optional non-pharmaceutical
#' intervention and an optional vaccination regime.
#'
#' This function is intended to only be called internally from
#' [model_default_cpp()].
#'
#' @param initial_state A matrix for the initial state of the compartments.
#' @param transmissibility The transmission rate \eqn{\beta} at which
#' unvaccinated and partially vaccinated individuals are infected by the
#' disease.
#' @param infectiousness_rate The rate of transition from exposed to infectious
#' \eqn{\alpha}.
#' @param recovery_rate The recovery rate \eqn{\gamma}.
#' @param contact_matrix The population contact matrix.
#' @param npi_time_begin The start time of any non-pharmaceutical interventions
#' .
#' @param npi_time_end The end time of any non-pharmaceutical interventions.
#' @param npi_cr The reduction in contacts from any non-pharmaceutical
#' interventions.
#' @param vax_time_begin The start time of any vaccination campaigns.
#' @param vax_time_end The end time of any vaccination campaigns.
#' @param vax_nu The vaccination rate of any vaccination campaigns.
#' @param rate_interventions A named list of `<rate_intervention>` objects.
#' @param time_dependence A named list of functions for parameter time
#' dependence.
#' @param time_end The end time of the simulation.
#' @param increment The time increment of the simulation.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix (see [population()]).
#' The second list element is a vector of timesteps.
#' @keywords internal
.model_default_cpp <- function(initial_state, transmissibility, infectiousness_rate, recovery_rate, contact_matrix, npi_time_begin, npi_time_end, npi_cr, vax_time_begin, vax_time_end, vax_nu, rate_interventions, time_dependence, time_end = 100.0, increment = 1.0) {
    .Call(`_epidemics_model_default_cpp_internal`, initial_state, transmissibility, infectiousness_rate, recovery_rate, contact_matrix, npi_time_begin, npi_time_end, npi_cr, vax_time_begin, vax_time_end, vax_nu, rate_interventions, time_dependence, time_end, increment)
}

#' @title Run the RIVM Vacamole model
#'
#' @description Vacamole is a deterministic, compartmental epidemic model built
#' by Kylie Ainslie and others at RIVM, the Dutch Public Health Institute for
#' the Covid-19 pandemic, with a focus on scenario modelling for
#' hospitalisation and vaccination.
#' Model code: https://github.com/kylieainslie/vacamole
#' Manuscript describing the model and its application:
#' https://doi.org/10.2807/1560-7917.ES.2022.27.44.2101090
#' This function is intended to only be called internally from
#' [model_vacamole_cpp()].
#'
#' @param initial_state A matrix for the initial state of the compartments.
#' @param transmissibility The transmission rate \eqn{\beta} at which
#' unvaccinated and partially vaccinated individuals are infected by the
#' disease.
#' @param transmissibility_vax The transmission rate \eqn{\beta_V} at which
#' individuals who have received two vaccine doses are infected by the disease.
#' @param infectiousness_rate The rate of transition from exposed to infectious
#' \eqn{\alpha}.
#' This is common to fully susceptible, partially vaccinated, and fully
#' vaccinated individuals (where fully vaccinated represents two doses).
#' @param mortality_rate The mortality rate of fully susceptible and partially
#' vaccinated and unprotected individuals.
#' @param mortality_rate_vax The mortality rate of individuals who are
#' protected by vaccination.
#' @param hospitalisation_rate The hospitalisation rate of fully susceptible
#' and partially vaccinated and unprotected individuals.
#' @param hospitalisation_rate_vax The hospitalisation rate of individuals who
#' are protected by vaccination.
#' @param recovery_rate The recovery rate \eqn{\gamma}.
#' @param contact_matrix The population contact matrix.
#' @param npi_time_begin The start time of any non-pharmaceutical interventions
#' .
#' @param npi_time_end The end time of any non-pharmaceutical interventions.
#' @param npi_cr The reduction in contacts from any non-pharmaceutical
#' interventions.
#' @param vax_time_begin The start time of any vaccination campaigns.
#' @param vax_time_end The end time of any vaccination campaigns.
#' @param vax_nu The vaccination rate of any vaccination campaigns.
#' @param rate_interventions A named list of `<rate_intervention>` objects.
#' @param time_dependence A named list of functions for parameter time
#' dependence.
#' @param time_end The end time of the simulation.
#' @param increment The time increment of the simulation.
#' @return A two element list, where the first element is a list of matrices
#' whose elements correspond to the numbers of individuals in each compartment
#' as specified in the initial conditions matrix (see [population()]).
#' The second list element is a vector of timesteps.
#' @keywords internal
.model_vacamole_cpp <- function(initial_state, transmissibility, transmissibility_vax, infectiousness_rate, mortality_rate, mortality_rate_vax, hospitalisation_rate, hospitalisation_rate_vax, recovery_rate, contact_matrix, npi_time_begin, npi_time_end, npi_cr, vax_time_begin, vax_time_end, vax_nu, rate_interventions, time_dependence, time_end = 100.0, increment = 1.0) {
    .Call(`_epidemics_model_vacamole_cpp_internal`, initial_state, transmissibility, transmissibility_vax, infectiousness_rate, mortality_rate, mortality_rate_vax, hospitalisation_rate, hospitalisation_rate_vax, recovery_rate, contact_matrix, npi_time_begin, npi_time_end, npi_cr, vax_time_begin, vax_time_end, vax_nu, rate_interventions, time_dependence, time_end, increment)
}

#' @title Compute the discrete probability of the truncated Erlang distribution
#' @name prob_discrete_erlang
#' @rdname prob_discrete_erlang
#'
prob_discrete_erlang_cpp <- function(shape, rate) {
    .Call(`_epidemics_prob_discrete_erlang_cpp`, shape, rate)
}

