# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Run an age-structured SEIR epidemic model
#'
#' @param population An object of the `population` class, which holds a
#' population contact matrix, a demography vector, and the initial conditions
#' of each demographic group. See [population()].
#' @param beta The transmission rate \eqn{\beta}.
#' @param alpha The rate of transition from exposed to infectious \eqn{\alpha}.
#' @param gamma The recovery rate \eqn{\gamma}.
#' @param time_end The maximum time, defaults to 200.0.
#' @param intervention A non-pharamaceutical intervention applied during the
#' course of the epidemic, with a start and end time, and age-specific effect
#' on contacts. See [intervention()].
#' @param increment The increment time, defaults to 0.1.
.epidemic_default_cpp <- function(population, beta, alpha, gamma, intervention, time_end = 200.0, increment = 0.1) {
    .Call(`_epidemics_epidemic_default_cpp`, population, beta, alpha, gamma, intervention, time_end, increment)
}

